### ISSUE TITLE
아이템 관련 issue 2

### ISSUE THREAD

**Issue by ozyeon** [CSID-DGU/2018-1-OSSP-OILSAO-9#2]
아이템 구현시 패널티 아이템에 대한 문제가 제기되었습니다. 플레이어가 패널티 아이템을 획득하지 않고 피해다니기만 한다면 패널티 아이템 구현 자체에 별 의미가 없다는 의견이 있었습니다. 따라서, 패널티/어드밴티지 아이템을 따로따로 구현하되, 플레이 화면에서는 공 크기증가/감소, 공 속도증가/감소 등의 반대 기능을 하는 아이템을 구별할 수 없게 똑같은 모양의 아이템으로 출현시켜 플레이어가 어떤 기능을 하는 아이템인지 모르는 상태로 아이템을 획득할 수 있도록 하는 것이 어떨까요? 더 좋은 의견 있으시면 말씀해주세요.

**Comment by Kimsunghyunny** [comment]
좋은 의견입니다. 그 의견에 따라서 공크기 관련 아이템은 그렇게 구현하기로 하고, 플레이어 속도 관련 아이템도 그와 같이 구현하면 좋을것 같습니다.

**Comment by ozyeon** [comment]
확인하였습니다. 해당 방향으로 진행하도록 하겠습니다.
